### ISSUE TITLE
Error on meteor install

### ISSUE THREAD

**Issue by wcousin** [StephenGrider/MeteorCasts#1]
I keep getting this error when installing meteor with terminal:

Wills-MacBook-Air:meteor WillCousin$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0  14058      0 --:--:-- --:--:-- --:--:-- 14079
Removing your existing Meteor installation.
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.4.2.3 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.

To get started fast:

  $ meteor create ~/my_cool_app
  $ cd ~/my_cool_app
  $ meteor

Or see the docs at:

  docs.meteor.com

Wills-MacBook-Air:meteor WillCousin$ meteor create images
You can't create a Meteor project inside another Meteor project.
Wills-MacBook-Air:meteor WillCousin$ cd images
Wills-MacBook-Air:images WillCousin$ meteor
[[[[[ ~/Desktop/meteor/images ]]]]]           

=> Started proxy.                             
=> Started MongoDB.                                                             
W20170109-18:34:32.542(-6)? (STDERR) /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:348
W20170109-18:34:32.591(-6)? (STDERR) }).run();
W20170109-18:34:32.591(-6)? (STDERR)    ^
W20170109-18:34:32.592(-6)? (STDERR) 
W20170109-18:34:32.592(-6)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170109-18:34:32.593(-6)? (STDERR) directory. Please run the following command to install it:
W20170109-18:34:32.594(-6)? (STDERR) 
W20170109-18:34:32.595(-6)? (STDERR)   meteor npm install --save babel-runtime
W20170109-18:34:32.596(-6)? (STDERR) 
W20170109-18:34:32.597(-6)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170109-18:34:32.597(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170109-18:34:32.598(-6)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170109-18:34:32.599(-6)? (STDERR)     at packages/babel-runtime.js:139:15
W20170109-18:34:32.599(-6)? (STDERR)     at packages/babel-runtime.js:150:3
W20170109-18:34:32.599(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:295:34
W20170109-18:34:32.599(-6)? (STDERR)     at Array.forEach (native)
W20170109-18:34:32.600(-6)? (STDERR)     at Function._.each._.forEach (/Users/WillCousin/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170109-18:34:32.600(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:128:5
W20170109-18:34:32.600(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:344:5
=> Exited with code: 1
W20170109-18:34:34.089(-6)? (STDERR) /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:348
W20170109-18:34:34.090(-6)? (STDERR) }).run();
W20170109-18:34:34.090(-6)? (STDERR)    ^
W20170109-18:34:34.091(-6)? (STDERR) 
W20170109-18:34:34.091(-6)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170109-18:34:34.091(-6)? (STDERR) directory. Please run the following command to install it:
W20170109-18:34:34.092(-6)? (STDERR) 
W20170109-18:34:34.093(-6)? (STDERR)   meteor npm install --save babel-runtime
W20170109-18:34:34.093(-6)? (STDERR) 
W20170109-18:34:34.093(-6)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170109-18:34:34.094(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170109-18:34:34.094(-6)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170109-18:34:34.095(-6)? (STDERR)     at packages/babel-runtime.js:139:15
W20170109-18:34:34.095(-6)? (STDERR)     at packages/babel-runtime.js:150:3
W20170109-18:34:34.096(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:295:34
W20170109-18:34:34.098(-6)? (STDERR)     at Array.forEach (native)
W20170109-18:34:34.099(-6)? (STDERR)     at Function._.each._.forEach (/Users/WillCousin/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170109-18:34:34.100(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:128:5
W20170109-18:34:34.102(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:344:5
=> Exited with code: 1
W20170109-18:34:35.247(-6)? (STDERR) /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:348
W20170109-18:34:35.247(-6)? (STDERR) }).run();
W20170109-18:34:35.248(-6)? (STDERR)    ^
W20170109-18:34:35.248(-6)? (STDERR) 
W20170109-18:34:35.248(-6)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20170109-18:34:35.249(-6)? (STDERR) directory. Please run the following command to install it:
W20170109-18:34:35.250(-6)? (STDERR) 
W20170109-18:34:35.250(-6)? (STDERR)   meteor npm install --save babel-runtime
W20170109-18:34:35.251(-6)? (STDERR) 
W20170109-18:34:35.251(-6)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
W20170109-18:34:35.251(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170109-18:34:35.252(-6)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170109-18:34:35.252(-6)? (STDERR)     at packages/babel-runtime.js:139:15
W20170109-18:34:35.252(-6)? (STDERR)     at packages/babel-runtime.js:150:3
W20170109-18:34:35.253(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:295:34
W20170109-18:34:35.253(-6)? (STDERR)     at Array.forEach (native)
W20170109-18:34:35.254(-6)? (STDERR)     at Function._.each._.forEach (/Users/WillCousin/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170109-18:34:35.255(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:128:5
W20170109-18:34:35.255(-6)? (STDERR)     at /Users/WillCousin/Desktop/meteor/images/.meteor/local/build/programs/server/boot.js:344:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by wcousin** [comment]
Looks like I may have figured it out by running meteor npm install --save babel-runtime
